hdt_arm:
  hardware_interface:
    loop_hz: 20
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
      - joint8
      - joint9
      - joint10
    joint1:
      addr: 1
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    joint2:
      addr: 2
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    joint3:
      addr: 3
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    joint4:
      addr: 4
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    joint5:
      addr: 5
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    joint6:
      addr: 6
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    joint7:
      addr: 7
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    joint8:
      addr: 8
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    joint9:
      addr: 9
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    joint10:
      addr: 10
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
