controller_list:
  - name: fake_left_arm_controller
    joints:
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - leftjoint6
  - name: fake_right_arm_controller
    joints:
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
      - rightjoint5
      - rightjoint6
  - name: fake_left_hand_controller
    joints:
      - leftpincer_joint
  - name: fake_right_hand_controller
    joints:
      - rightpincer_joint
  - name: fake_dual_arm_controller
    joints:
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - leftjoint6
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
      - rightjoint5
      - rightjoint6
  - name: fake_dual_hand_controller
    joints:
      - leftpincer_joint
      - rightpincer_joint
initial:  # Define initial robot poses.
#  - group: left_arm
#    pose: home
