# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  leftjoint1:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint2:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint3:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint4:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint5:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  leftjoint6:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  leftpincer_joint:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  leftpincerfinger_left:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  leftpincerfinger_right:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint1:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint2:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint3:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint4:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint5:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  rightjoint6:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  rightpincer_joint:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  rightpincerfinger_left:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0
  rightpincerfinger_right:
    has_velocity_limits: true
    max_velocity: 0.785398163397
    has_acceleration_limits: false
    max_acceleration: 0