<?xml version="1.0"?>
<robot name="hdt_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- constants -->
    <xacro:property name="M_PI" value="3.1415926535897931"/>
    <xacro:property name="pos_limit" value="${8*M_PI}"/>


    <!-- mechanical constants -->
    <xacro:property name="drive_length" value="0.03855"/>
    <xacro:property name="drive_offset" value="0.02455"/>
    <xacro:property name="tube_diameter" value="0.0515"/>
    <xacro:property name="tube1_length" value="0.349546"/>
    <xacro:property name="tube2_length" value="0.33294"/>
    <xacro:property name="pedestal_to_drive" value="0.05515"/>
    <xacro:property name="drive_to_drive" value="0.06275"/>
    <xacro:property name="prox_span" value="0.3004"/>
    <xacro:property name="drive_to_box" value="0.03865"/>
    <xacro:property name="box_tilt" value="0.471238898"/>
    <xacro:property name="box_length" value="0.080"/>
    <xacro:property name="box_to_drive" value="0.03517"/>
    <xacro:property name="distal_mid" value="0.07295"/>
    <xacro:property name="distal_length" value="0.13825"/>
    <xacro:property name="finger_forward" value="0.036761"/>
    <xacro:property name="finger_lateral" value="0.0135"/>
  
    <!-- control constants -->  
    <xacro:property name="drive_velocity" value="${M_PI/4}"/>

    <!-- materials -->
    <material name="drive_color">
        <color rgba="${250/255} ${167/255} ${91/255} 1.0"/>
    </material>

    <material name="link_color">
        <color rgba="${204/255} ${204/255} ${204/255} 1.0"/>
    </material>

    <material name="finger_color">
        <color rgba="${112/255} ${195/255} ${106/255} 1.0"/>
    </material>

    <xacro:property name="A24_pincer_ratio" value="0.86" />

    <!--A35 drive simplified collision properties-->
    <xacro:property name="A24_collision_radius" value="0.025"/>
    <xacro:property name="A24_collision_length" value="0.07"/>
    <xacro:property name="A24_collision_offset" value="-0.01"/>

     <!-- default inertia -->
     <xacro:macro name="default_inertia">
           <inertia
           ixx="0.005" ixy="0.0" ixz="0.0"
           iyy="0.005" iyz="0.0"
           izz="0.005"/>
     </xacro:macro>

    <!-- segment 0 -->
    <link name="base_link"/>

    <!-- pedestal -->
    <joint name="pedestal_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="pedestal_link"/>
    </joint>

    <link name="pedestal_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H021285 - SHAREABLE - A24 Q PEDESTAL ASSY - EMD_1.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H021285 - SHAREABLE - A24 Q PEDESTAL ASSY - EMD_1.STL"/>
            </geometry>
            <material name="link_color"/>
        </visual>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

    <!-- drive 1 -->
    <joint name="joint1" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="${-pos_limit}" upper="${pos_limit}" velocity="${drive_velocity}"/>
        <origin xyz="0 0 ${pedestal_to_drive}" rpy="0 0 ${-M_PI/2}"/>
        <parent link="pedestal_link"/>
        <child link="drive1_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive1_link">
      <collision>
        <origin xyz="0 0 ${A24_collision_offset}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${A24_collision_radius}" length="${A24_collision_length}"/>
        </geometry>
      </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H020840 - SHAREABLE - A24 DRIVE MODULE - EMD_1.STL"/>
            </geometry>
            <material name="drive_color"/>
        </visual>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

    <!-- drive 2 -->
    <joint name="joint2" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="${-M_PI/2}" upper="${M_PI/2}" velocity="${drive_velocity}"/>
        <origin xyz="${drive_to_drive} 0 0" rpy="${M_PI} ${-M_PI/2} 0"/>
        <parent link="drive1_link"/>
        <child link="drive2_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive2_link">
      <collision>
        <origin xyz="0 0 ${A24_collision_offset}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${A24_collision_radius}" length="${A24_collision_length}"/>
        </geometry>
      </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H020840 - SHAREABLE - A24 DRIVE MODULE - EMD_1.STL"/>
            </geometry>
            <material name="drive_color"/>
        </visual>
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

    <!-- proximal tube -->
    <joint name="proximal_tube_joint" type="fixed">
        <origin xyz="${prox_span/2} 0 0" rpy="0 0 0" />
        <parent link="drive2_link"/>
        <child link="proximal_tube_link"/>
    </joint>

    <link name="proximal_tube_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H021435 - SHAREABLE - A24 PROXIMAL TUBE ASSY - EMD_1.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
               <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H021435 - SHAREABLE - A24 PROXIMAL TUBE ASSY - EMD_1.STL"/>
            </geometry>
            <material name="link_color"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>


    <!-- drive 3 link - place holder for drive housing model -->
    <joint name="drive3_housing_joint" type="fixed">
        <origin xyz="${prox_span/2} 0 0" rpy="0 0 ${M_PI}"/>
        <parent link="proximal_tube_link"/>
        <child link="drive3_housing_link"/>
    </joint>

    <link name="drive3_housing_link">
      <collision>
        <origin xyz="0 0 ${A24_collision_offset}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${A24_collision_radius}" length="${A24_collision_length}"/>
        </geometry>
      </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
               <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H020840 - SHAREABLE - A24 DRIVE MODULE - EMD_1.STL"/>
            </geometry>
            <material name="drive_color"/>
        </visual>

    </link>

    
  <!-- drive 3 -->
    <joint name="joint3" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="-1.5708" upper="3.5" velocity="${drive_velocity}"/>
        <origin xyz="0 0 0" rpy="0 0 ${box_tilt-M_PI}"/>
        <parent link="drive3_housing_link"/>
        <child link="drive3_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive3_link">
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>
 
  <!-- elbow box -->
    <joint name="elbow_box_joint" type="fixed">
        <origin xyz="0 0 ${-drive_to_box}" rpy="0 0 ${-M_PI/2}"/>
        <parent link="drive3_link"/>
        <child link="elbow_box_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="elbow_box_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H021330 - SHAREABLE - A24 CRS-I ELBOW BRACKET COMPUTER ASSY - EMD_1.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
               <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H021330 - SHAREABLE - A24 CRS-I ELBOW BRACKET COMPUTER ASSY - EMD_1.STL"/>
            </geometry>
            <material name="link_color"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>
    
<!-- drive 4 link - place holder for drive housing model -->
    <joint name="drive4_housing_joint" type="fixed">
        <origin xyz="${box_length} 0 ${box_to_drive}" rpy="0 ${M_PI/2} ${M_PI-box_tilt}"/>
        <parent link="elbow_box_link"/>
        <child link="drive4_housing_link"/>
    </joint>

    <link name="drive4_housing_link">
      <collision>
        <origin xyz="0 0 ${A24_collision_offset}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${A24_collision_radius}" length="${A24_collision_length}"/>
        </geometry>
      </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
               <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H020840 - SHAREABLE - A24 DRIVE MODULE - EMD_1.STL"/>
            </geometry>
            <material name="drive_color"/>
        </visual>

    </link>

    
  <!-- drive 4 -->
    <joint name="joint4" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="${-pos_limit}" upper="${pos_limit}" velocity="${drive_velocity}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="drive4_housing_link"/>
        <child link="drive4_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive4_link">
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>
 

<!-- distal tube -->
    <joint name="distal_tube_joint" type="fixed">
        <origin xyz="0 0 ${-distal_mid}" rpy="0 0 0" />
        <parent link="drive4_link"/>
        <child link="distal_tube_link"/>
    </joint>

    <link name="distal_tube_link">
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
            <geometry>
                <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H021436 - SHAREABLE - A24 DISTAL TUBE ASSY - EMD_1.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="${M_PI} 0 0"/>
            <geometry>
               <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H021436 - SHAREABLE - A24 DISTAL TUBE ASSY - EMD_1.STL"/>
            </geometry>
            <material name="link_color"/>
        </visual>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>


    <!-- drive 5 link - place holder for drive housing model -->
    <joint name="drive5_housing_joint" type="fixed">
        <origin xyz="0 0 ${-distal_length + distal_mid}" rpy="0 ${-M_PI/2} 0"/>
        <parent link="distal_tube_link"/>
        <child link="drive5_housing_link"/>
    </joint>

    <link name="drive5_housing_link">
      <collision>
        <origin xyz="0 0 ${A24_collision_offset}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${A24_collision_radius}" length="${A24_collision_length}"/>
        </geometry>
      </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
               <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H020840 - SHAREABLE - A24 DRIVE MODULE - EMD_1.STL"/>
            </geometry>
            <material name="drive_color"/>
        </visual>

    </link>

    
  <!-- drive 5 -->
    <joint name="joint5" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="-2.3" upper="2.3" velocity="${drive_velocity}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="drive5_housing_link"/>
        <child link="drive5_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive5_link">
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

    <!-- drive 6 link - place holder for drive housing model -->
    <joint name="drive6_housing_joint" type="fixed">
        <origin xyz="0 0 ${-drive_to_drive}" rpy="0 ${-M_PI/2} ${M_PI}"/>
        <parent link="drive5_link"/>
        <child link="drive6_housing_link"/>
    </joint>

    <link name="drive6_housing_link">
      <collision>
        <origin xyz="0 0 ${A24_collision_offset}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${A24_collision_radius}" length="${A24_collision_length}"/>
        </geometry>
      </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
               <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H020840 - SHAREABLE - A24 DRIVE MODULE - EMD_1.STL"/>
            </geometry>
            <material name="drive_color"/>
        </visual>

    </link>

    
  <!-- drive 6 -->
    <joint name="joint6" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="${-pos_limit}" upper="${pos_limit}" velocity="${drive_velocity}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="drive6_housing_link"/>
        <child link="drive6_link"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>

    <link name="drive6_link">
        
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

<!-- pincer link - place holder for pincer housing model -->
    <joint name="pincer_housing_joint" type="fixed">
        <origin xyz="0 0 ${-drive_to_drive}" rpy="0 ${-M_PI/2} 0"/>
        <parent link="drive6_link"/>
        <child link="pincer_housing_link"/>
    </joint>

    <link name="pincer_housing_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H021094 - SHAREABLE - A24-P PINCER ASSY, NO FINGERS - EMD_1.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
               <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H021094 - SHAREABLE - A24-P PINCER ASSY, NO FINGERS - EMD_1.STL"/>
            </geometry>
            <material name="drive_color"/>
        </visual>

    </link>

    <!-- Pincer joint, nothing connected to output link use mimic joints to account for gear ratio beteen output and fingers -->
    <joint name="pincer_joint" type="revolute">
        <hdt id="10" kmin="75" kmax="150" inertia="0.075"/>		
        <axis xyz="0 0 1"/>
        <limit effort="48.0" lower="-0.2" upper="0.9" velocity="${M_PI/4}"/>
        <origin xyz="0.0135 0 0.0375" rpy="0 0 0"/> 
        <parent link="pincer_housing_link"/>
        <child link="pincer_output"/>
        <dynamics damping="0.7" friction="0.0"/>
    </joint>
    
    <link name="pincer_output">
    </link>
    
  <!-- pincer finger left -->
    <joint name="pincerfinger_left" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="0" upper="${M_PI/2}" velocity="${drive_velocity}"/>
        <origin xyz="${-finger_forward} ${-finger_lateral} 0" rpy="0 0 ${-M_PI}"/>
        <parent link="pincer_housing_link"/>
        <child link="pincerfinger_left_link"/>
        <dynamics damping="0.7" friction="0.0"/>
        <mimic joint="pincer_joint" multiplier="${A24_pincer_ratio}" offset="0.0"/>
    </joint>

    <link name="pincerfinger_left_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H020868 - SHAREABLE - A24-P PINCER FINGER, OVERMOLD ASSY - EMD_1.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
               <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H020868 - SHAREABLE - A24-P PINCER FINGER, OVERMOLD ASSY - EMD_1.STL"/>
            </geometry>
            <material name="finger_color"/>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

<!-- pincer finger left -->
    <joint name="pincerfinger_right" type="revolute">
        <axis xyz="0 0 1"/>
        <limit effort="60.0" lower="${-2*M_PI}" upper="${2*M_PI}" velocity="${drive_velocity}"/>
        <origin xyz="${-finger_forward} ${finger_lateral} 0" rpy="${M_PI} 0 ${-M_PI}"/>
        <parent link="pincer_housing_link"/>
        <child link="pincerfinger_right_link"/>
        <dynamics damping="0.7" friction="0.0"/>
        <mimic joint="pincer_joint" multiplier="${A24_pincer_ratio}" offset="0.0"/>
    </joint>

    <link name="pincerfinger_right_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H020868 - SHAREABLE - A24-P PINCER FINGER, OVERMOLD ASSY - EMD_1.STL"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
               <mesh filename="package://hdt_6dof_a24_pincer_description/meshes/H020868 - SHAREABLE - A24-P PINCER FINGER, OVERMOLD ASSY - EMD_1.STL"/>
            </geometry>
            <material name="finger_color"/>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0"/>
            <xacro:default_inertia />
        </inertial>
    </link>

    <!-- endpoint -->
    <joint name="endpoint_joint" type="fixed">
        <origin xyz="-0.15 0 0" rpy="0 0 ${M_PI}"/>
        <parent link="pincer_housing_link"/>
        <child link="endpoint_link"/>
    </joint>

    <link name="endpoint_link">
    </link>
</robot>

