hdt_arm:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20
    
  leftjoint1_position_controller:
    type: position_controllers/JointPositionController
    joint: leftjoint1
  leftjoint2_position_controller:
    type: position_controllers/JointPositionController
    joint: leftjoint2
  leftjoint3_position_controller:
    type: position_controllers/JointPositionController
    joint: leftjoint3
  leftjoint4_position_controller:
    type: position_controllers/JointPositionController
    joint: leftjoint4
  leftjoint5_position_controller:
    type: position_controllers/JointPositionController
    joint: leftjoint5
  leftjoint6_position_controller:
    type: position_controllers/JointPositionController
    joint: leftjoint6
  leftpincer_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: leftpincer_joint
    
  leftjoint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: leftjoint1
  leftjoint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: leftjoint2
  leftjoint3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: leftjoint3
  leftjoint4_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: leftjoint4
  leftjoint5_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: leftjoint5
  leftjoint6_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: leftjoint6
  leftpincer_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: leftpincer_joint
    
  rightjoint1_position_controller:
    type: position_controllers/JointPositionController
    joint: rightjoint1
  rightjoint2_position_controller:
    type: position_controllers/JointPositionController
    joint: rightjoint2
  rightjoint3_position_controller:
    type: position_controllers/JointPositionController
    joint: rightjoint3
  rightjoint4_position_controller:
    type: position_controllers/JointPositionController
    joint: rightjoint4
  rightjoint5_position_controller:
    type: position_controllers/JointPositionController
    joint: rightjoint5
  rightjoint6_position_controller:
    type: position_controllers/JointPositionController
    joint: rightjoint6
  rightpincer_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: rightpincer_joint
    
  rightjoint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: rightjoint1
  rightjoint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: rightjoint2
  rightjoint3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: rightjoint3
  rightjoint4_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: rightjoint4
  rightjoint5_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: rightjoint5
  rightjoint6_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: rightjoint6
  rightpincer_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: rightpincer_joint
    
  left_arm_controller:
    type: position_controllers/JointTrajectoryController
    state_publish_rate: 20
    joints:
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - leftjoint6
  right_arm_controller:
    type: position_controllers/JointTrajectoryController
    state_publish_rate: 20
    joints:
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
      - rightjoint5
      - rightjoint6
    constraints:
      goal_time: 5.0
      leftjoint1:
        trajectory: 0.2618
        goal:       0.0873
      leftjoint2:
        trajectory: 0.2618
        goal:       0.0873
      leftjoint3:
        trajectory: 0.2618
        goal:       0.0873
      leftjoint4:
        trajectory: 0.2618
        goal:       0.0873
      leftjoint5:
        trajectory: 0.2618
        goal:       0.0873
      leftjoint6:
        trajectory: 0.2618
        goal:       0.0873

      rightjoint1:
        trajectory: 0.2618
        goal:       0.0873
      rightjoint2:
        trajectory: 0.2618
        goal:       0.0873
      rightjoint3:
        trajectory: 0.2618
        goal:       0.0873
      rightjoint4:
        trajectory: 0.2618
        goal:       0.0873
      rightjoint5:
        trajectory: 0.2618
        goal:       0.0873
      rightjoint6:
        trajectory: 0.2618
        goal:       0.0873
