hdt_arm:
  hardware_interface:
    loop_hz: 20
    joints:
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - leftjoint6
      - leftpincer_joint
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
      - rightjoint5
      - rightjoint6
      - rightpincer_joint
    leftjoint1:
      addr: 1
      namespace: "left_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    leftjoint2:
      addr: 2
      namespace: "left_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    leftjoint3:
      addr: 3
      namespace: "left_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    leftjoint4:
      addr: 4
      namespace: "left_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    leftjoint5:
      addr: 5
      namespace: "left_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    leftjoint6:
      addr: 6
      namespace: "left_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    leftpincer_joint:
      addr: 10
      namespace: "left_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    rightjoint1:
      addr: 11
      namespace: "right_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    rightjoint2:
      addr: 12
      namespace: "right_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    rightjoint3:
      addr: 13
      namespace: "right_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    rightjoint4:
      addr: 14
      namespace: "right_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    rightjoint5:
      addr: 15
      namespace: "right_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    rightjoint6:
      addr: 16
      namespace: "right_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
    rightpincer_joint:
      addr: 20
      namespace: "right_arm"
      kmin: 100.0
      kmax: 200.0
      inertia: 0.1
